name: jose
description: Javascript Object Signing and Encryption (JOSE) library supporting JWE, JWS, JWK and JWT
version: 0.3.2
homepage: https://github.com/appsup-dart/jose

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto_keys: '>=0.2.0 <0.3.0'
  meta: ^1.1.6
  typed_data: ^1.0.0
  x509: ^0.2.1
  http: ^0.12.0+2
  http_parser: ^3.1.4
  asn1lib: ^0.8.1
  collection: ^1.14.13

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
